### ISSUE TITLE
iptables_service fails under Chef 16.13 with undefined method `new_resource' for Chef::Resource::Service

### ISSUE THREAD

**Issue by jgitlin-p21** [chef-cookbooks/iptables#129]
Under Cinc / Chef 16.13, the following block

```
iptables_service 'iptables services ipv4' do

end
```

Fails to converge with

```
  * iptables_service[iptables services ipv4] action enable[2021-05-05T16:43:20+00:00] INFO: Processing iptables_service[iptables services ipv4] action enable (general::iptables_block_all line 96)

    
    ================================================================================
    Error executing action `enable` on resource 'iptables_service[iptables services ipv4]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `new_resource' for Chef::Resource::Service
    
    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /var/cinc/cache/cookbooks/iptables/resources/service.rb:65:in `block (3 levels) in class_from_file'
    /var/cinc/cache/cookbooks/iptables/resources/service.rb:64:in `block (2 levels) in class_from_file'
    /var/cinc/cache/cookbooks/iptables/resources/service.rb:63:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/cinc/cache/cookbooks/general/recipes/iptables_block_all.rb
    
     96: iptables_service 'iptables services ipv4' do
     97:   @message = "Applied firewall rules"
     98: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/cinc/cache/cookbooks/general/recipes/iptables_block_all.rb:96:in `from_file'
    
    iptables_service("iptables services ipv4") do
      action [:enable]
      default_guard_interpreter :default
      declared_type :iptables_service
      cookbook_name "general"
      recipe_name "iptables_block_all"
      message "Applied firewall rules"
      config_file "/etc/sysconfig/iptables"
      sysconfig_file "/etc/sysconfig/iptables-config"
      sysconfig {"IPTABLES_MODULES"=>"", "IPTABLES_MODULES_UNLOAD"=>"no", "IPTABLES_SAVE_ON_STOP"=>"no", "IPTABLES_SAVE_ON_RESTART"=>"no", "IPTABLES_SAVE_COUNTER"=>"no", "IPTABLES_STATUS_NUMERIC"=>"yes", "IPTABLES_STATUS_VERBOSE"=>"no", "IPTABLES_STATUS_LINENUMBERS"=>"yes"}
      service_name "iptables"
    end
    
    System Info:
    ------------
    chef_version=16.13.16
    platform=amazon
    platform_version=2
    ruby=ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [aarch64-linux]
    program_name=/usr/bin/cinc-client
    executable=/opt/cinc/bin/cinc-client
```

**Comment by jgitlin-p21** [comment]
Discussed with #sous-chefs slack channel and @bmhughes kindly provided me the fixed code; Submitting a PR shortly!
